### ISSUE TITLE
Problems with Spaces in Paths

### ISSUE THREAD

**Issue by docluv** [jfromaniello/RazorCandle#1]
when I run it with a space in my path I am getting an error. Was able to run successfully when I removed or moved the source files to a path without a space in it.

**Comment by jfromaniello** [comment]
ups! even with double quotes:

razorcandle.exe "c:\bla bla bla\ blo    ble.cshtml"

thanks

**Comment by jfromaniello** [comment]
I just fixed.. there was a problem with the way c# parses command line arguments. It should work fine now. 

You can download the new exe from this page. 

Thanks for reporting,

**Comment by docluv** [comment]
Thnx I will get it in the morning

Sent from my Windows Phone
